version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hk123
    command: --serviceExecutor adaptive

  elasticsearch:
    image: elasticsearch:7.9.3
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - '5601:5601'
    environment:
      ELASTICSEARCH_URL: http://localhost:9200/